Fix: Reference to existing myvenv directory
DjangoGirls/tutorial pull request #1753
Opened 2021-12-26 21:49 UTC by adamantike

The directory we have previously created is called `myvenv`, not `venv`.

2021-12-26 23:15 UTC, das-g requested changes

2021-12-26 23:15 UTC, das-g commented on es/python_introduction/README.md
> +{% filename %}{{ warning_icon }} command-line{% endfilename %}
This change seems unrelated.

2021-12-27 05:51 UTC, adamantike commented on es/python_introduction/README.md
> +{% filename %}{{ warning_icon }} command-line{% endfilename %}
Reverted!

2021-12-27 09:33 UTC, das-g approved these changes

2021-12-27 09:33 UTC, merged