Ignore the default branch name problem
DjangoGirls/tutorial pull request #1780
Opened 2022-12-01 19:10 UTC by ekohl

With older versions of git the command to rename the branch fails if there is no branch yet. We're also making the tutorial harder than it needs to be.

This ignores it and simply uses the default by pushing HEAD instead of main. GitHub is then smart enough to use that as default. Future clones will also simply copy the default branch from GitHub.

Fixes #1779

2022-12-01 19:19 UTC, nikhiljohn10 reviewed
LGTM

2022-12-01 19:28 UTC, ekohl commented on en/deploy/install_git.md
> -During installation, if you are presented with the option of "Adjusting the name of the initial branch in new repositories", please choose to "Override the default" and use "main". This will align yo
I have not checked about this question. Should we ignore it and assume users will keep the default value?

2022-12-01 23:18 UTC, das-g commented
As we give example output of `git status` and of `git push …`, shouldn't we at least mention that it might read `master` instead of `main` for some?

2023-08-21 06:12 UTC, elena requested changes
Discussing and DjangoGirlsAdelaide/PyConAU23 this is a far gnarlier problem than it might seem. The `main` branch conversation is very important to the community. Just deleting it as a concept doesn't feel right.. 

The real problem is that older versions of git are still initiating a repo on the branch master and git should be updated. Removing the documentation below just doesn't necessarily feel like the right approach, perhaps we could make this hiccup less confusing though -- let's keep having the conversation. 

[edit]: just some more background: 
python-core discussion: https://discuss.python.org/t/communitys-take-on-changing-master-branch-to-main/4462/11
from that thread: https://www.cnet.com/tech/computing/microsofts-github-is-removing-coding-terms-like-master-and-slave/

2023-08-22 11:07 UTC, ekohl commented
I respectfully disagree that it's a problem. The tutorial is already hard enough and adding more concepts just confuses people. They just have a single branch and that's good enough. They have so many new things coming at them at once that I'm sure nobody will even notice. And as time goes on, it'll simply disappear when more people have a newer git version.

But I'll also note that I'm of the opinion that it'll all virtue signalling and doesn't actually make any difference at all. It still annoys me on an almost daily basis that you now have to remember what the default branch is because only part of the world has switched over. Let's not punish the participants in the same way and make their lives a little bit easier.

2023-08-22 16:23 UTC, amakarudze reviewed
Seeing that only the Django Girls website now uses `main` as default branch while all other repos still use `master`, I am inclined to agree with all those who feel it is unnecessary to burden attendees with this. We can't really make life difficult for them when we have not completely made that change ourselves. They will still encounter `master` branch when they contribute to our repos.

Since we are already working on simplifying the tutorial, I agree with them just working with the default branch and then let them get involved in this discussion as they progress with their coding journey.

With that in mind, I would agree with adding the statement that their default branch maybe `master` or `main` in the Git section and we can merge this in.

2023-08-23 04:42 UTC, nikhiljohn10 commented
The movement to change the default branch name was driven by [this](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) as far as I know. Github, Gitlab and others are pushing the changes as they all felt the need for change. It is inevitable, the default branch name is going to be `main` in almost all maintained git software in the near future.

Also, I don't think that the name change is going to confuse them if we mention that "Currently, default branch name is `main` and previously it was `master`. You could encounter it in some repositories."

With that said, I hope we can merge this PR until/unless it affects any other technical aspects of DjangoGirls repos.

2023-09-26 11:11 UTC, ekohl commented
> If this specific approach is controversial and needs further consideration, perhaps in the meantime we could at least change the tutorial enough so people no longer face the error? There are two options that are really simple:

I don't think it's controversial: it works and makes lives easier.

You may see some cases where the exact example output may differ a little bit, but I doubt students will notice this.

Right now I'm providing a solution to a real problem. I don't see anyone else submitting any alternative. I'm getting really frustrated that there is no movement on this issue.

2023-09-27 06:37 UTC, thibaudcolas commented
@ekohl reading through #1676, #1742, #1779, and now this pull request – it seems reasonable to me to assume others feel differently about this than you do?

With the caveat that I don’t personally help maintain the tutorial – I’d suspect the main reason there’s no movement is that the solution you’re providing essentially undoes a lot of pre-existing work by other people. You’re also suggesting bigger changes (removing all notions of branch renaming for all tutorial users) than are strictly needed to address the problem at hand (make the branch renaming work for users below git 2.28).

I’ve proposed alternatives that I think are suitable right in the comment you’re responding to. I’ve made a PR for the one that has my preference at #1803 if it helps making it clearer it’s a suitable alternative.

2023-09-27 09:48 UTC, ekohl commented
> With the caveat that I don’t personally help maintain the tutorial – I’d suspect the main reason there’s no movement is that the solution you’re providing essentially undoes a lot of pre-existing work by other people. You’re also suggesting bigger changes (removing all notions of branch renaming for all tutorial users) than are strictly needed to address the problem at hand (make the branch renaming work for users below git 2.28).

Yes, and I see this as a feature. I've been a mentor at least 8 times and I always notice that most students are overloaded with new information. This is such an irrelevant point for them that it just distracts them from the real work. They can only learn so much in a single day, so let's make sure they learn Python, Django and HTML & CSS. At the events I attended I also heard regular suggestions to drop git, pushing to github & deploying altogether because it's too much and barely teaches them anything. I'm not that extreme, but I do think we should shield them from the default branch problem.

> I’ve proposed alternatives that I think are suitable right in the comment you’re responding to. I’ve made a PR for the one that has my preference at #1803 if it helps making it clearer it’s a suitable alternative.

While I disagree with it, I do appreciate you being constructive in presenting an alternative.

2023-09-27 10:53 UTC, amakarudze approved these changes
Merging this in to end this discussion now. We seem to be going back in circles and ending at the same solution or no solution at all.

2023-09-27 10:54 UTC, merged