Updated Ru translation of the installation instructions with python version variables
DjangoGirls/tutorial pull request #1810
Opened 2023-10-13 14:09 UTC by bp72

Changes in this pull request:

- Updated python and Django installation instructions with variables to match the English version
- Updated link for MacOS python download and the filenames

2023-10-13 21:44 UTC, b0g3r requested changes

2023-10-13 21:44 UTC, b0g3r commented on ru/python_installation/instructions.md
> +Если у тебя установлена другая версия Python, не меньше чем {{ book.py_min_version }} (например, {{ book.py_min_release }}), то нет необходимости обновляться.
Кажется тут во второй переменной должен быть py-release, проверишь?

2023-10-15 12:46 UTC, bp72 commented on ru/python_installation/instructions.md
> +Если у тебя установлена другая версия Python, не меньше чем {{ book.py_min_version }} (например, {{ book.py_min_release }}), то нет необходимости обновляться.
Привет, спасибо за ревью!
Здесь имеется в виду минимальная поддерживаемая версия, в отрендеренном виде выглядит так:
> Если у тебя установлена другая версия Python, не меньше чем 3.6 (например, 3.6.8), то нет необходимости обновляться. 

В `py_release` сейчас 3.8.6 - как я понимаю, это рекомендуемая версия или наиболее свежая, с которой тестировали туториал.

2023-10-15 12:55 UTC, b0g3r commented on ru/python_installation/instructions.md
> +Если у тебя установлена другая версия Python, не меньше чем {{ book.py_min_version }} (например, {{ book.py_min_release }}), то нет необходимости обновляться.
Спасибо, понял

2023-10-15 12:55 UTC, b0g3r approved these changes

2023-10-15 13:01 UTC, das-g commented on ru/python_installation/instructions.md
> +Если у тебя установлена другая версия Python, не меньше чем {{ book.py_min_version }} (например, {{ book.py_min_release }}), то нет необходимости обновляться.
Exactly. That's how the English original uses this, too:
https://github.com/DjangoGirls/tutorial/blob/cefc1c43db697dd33c7f970a330278f57835cd60/en/python_installation/instructions.md?plain=1#L54-L54

2023-10-15 13:01 UTC, merged